### ISSUE TITLE
Trying to fetch Multi topic In Local , But It is showing warning like this

### ISSUE THREAD

**Issue by parthasarathy93** [dibbhatt/kafka-spark-consumer#69]
WARN : consumer.kafka.ReceiverStreamListener - stop consumer as pending queue 4 greater than configured limit 3
WARN : consumer.kafka.ReceiverStreamListener - stop consumer as pending queue 5 greater than configured limit 3

**Comment by dibbhatt** [comment]
This is happening because your Spark Streaming batches are getting queued up and the consumer is applying the throttle to avoid memory pressure. You may need to tune your application to make sure a Spark Streaming Batch is completing within Batch Duration, otherwise the incoming batches will be in Pending queue. 

There is a property which controls this "consumer.queue.to.throttle" , default is 3. You can set this to higher limit to avoid this WARN logs. e.g. if you keep this value to say 10, after 10 batches are in Pending queue , you will get this WARN message.

Let me know if I am able to explain the logic.

**Comment by dibbhatt** [comment]
There are two property controls the poll volume.
min.poll.records -- Default os 50
max.poll.records -- Default is 500

Consumer normally poll at the rate set up by max.poll.records number. 

But when above throttle is applied, the consumer is reset to poll at Min rate. You can control this also adjusting above two settings. Say, if you are polling too much data , you can lower both min and max poll volume to avoid queue to build up.
