### ISSUE TITLE
How many KafkaReceiver do I need?

### ISSUE THREAD

**Issue by jedisct1** [dibbhatt/kafka-spark-consumer#8]
I am trying to read from a single topic, which has 100 partitions.

The description of Kafka-Spark-Consumer mentions:

    The logic will detect number of partitions for a topic and spawn that many Kafka Receivers.

But the example seems to suggest that the number of partitions has to be manually given, and that for each of them, a `KafkaReceiver` instance is required:

    val kafkaStreams = (1 to partitions).map { i=>
        ssc.receiverStream(new KafkaReceiver(props, i))
    }

Do I actually need to manually spawn 100 `KafkaReceiver` instances? Does it mean that 100 CPU cores have to be reserved to this?

It there a way to have receivers manage multiple partitions instead of having to spawn that many receivers?

Thanks in advance for your help.

**Comment by dibbhatt** [comment]
Hi Frank, 
Thanks for your email. You are correct. At this point , you need have as many Receivers as your number of partitions and all Receivers needs single core. 
But this can be overridden also. Even in our use case, there are few topic where message load is less and we want to create single Receiver for all partitiond. This can be done by modifying the KafkaReceiver.java. At present it creates singles KafkaConsumer thread for every partition and allocate a Receiver to it. Instead, we can create multiple instances of KafkaConsumer for a given range of partition, and assign to a Receiver. This is easily doable and we have a plan to implement it as I said. Do let me know if you need such feature, I can roll this out .
Regards, Dibyendu  


     On Monday, 30 March 2015 4:36 PM, Frank Denis <notifications@github.com> wrote:
   

 I am trying to read from a single topic, which has 100 partitions.The description of Kafka-Spark-Consumer mentions:The logic will detect number of partitions for a topic and spawn that many Kafka Receivers.
But the example seems to suggest that the number of partitions has to be manually given, and that for each of them, a KafkaReceiver instance is required:val kafkaStreams = (1 to partitions).map { i=>
    ssc.receiverStream(new KafkaReceiver(props, i))
}
Do I actually need to manually spawn 100 KafkaReceiver instances? Does it mean that 100 CPU cores have to be reserved to this?It there a way to have receivers manage multiple partitions instead of having to spawn that many receivers?Thanks in advance for your help.—

**Comment by jedisct1** [comment]
Hi Dibyendu,

Thanks for this project, and thanks a lot for your response, it really helps.

Having the ability to use a single thread for a range of partitions would be really awesome!

Right now, I have these 100 partitions and I don't have much control over this. But the load is very low and having 100 threads dedicated to receiving Kafka frames is way too much for the cluster.

**Comment by dibbhatt** [comment]
I understand..Let me give a day or two.. Will try to roll out a new Receiver which can handle partition range.
Dib 


     On Monday, 30 March 2015 6:35 PM, Frank Denis <notifications@github.com> wrote:
   

 Hi Dibyendu,Thanks for this project, and thanks a lot for your response, it really helps.Having the ability to use a single thread for a range of partitions would be really awesome!Right now, I have these 100 partitions and I don't have much control over this. But the load is very low and having 100 threads dedicated to receiving Kafka frames is way too much for the cluster.—

**Comment by jedisct1** [comment]
Really appreciate.

You rock, Dib.

**Comment by dibbhatt** [comment]
Hi, 

I have made the change in the Low Level Receiver where you can now specify the Number Of Receivers task you need for you Topic. You No Longer need to specify the number of Partition as it is automatically taken care.

If your number of Receiver if Less than your number of partition, every Receiver will handle a set of Partition to pull data from Kafka.

If your number of Receiver is equal to number of Partition, then every receiver will handle one partition. 

Java : 
JavaDStream<MessageAndMetadata> unionStreams = ReceiverLauncher.launch(jsc, props, numberOfReceivers);


Scala :

val tmp_stream = ReceiverLauncher.launch(ssc, props, numberOfReceivers)


Complete example is available here :

src/main/java/consumer/kafka/client/Consumer.java for Java based implementation

examples/scala/LowLevelKafkaConsumer.scala is a sample scala code on how to use this utility.


Note : If you need more finer control of your Receivers, you can directly use KafkaReceiver or KafkaRangeReceiver based on your use case . e.g.  you want to consume ONLY one Partition , or you want to consume ONLY a SUBSET of partition .

Regards, 
Dibyendu

**Comment by jedisct1** [comment]
![Who's awesome? You're awesome!](http://www.imgion.com/images/01/is-it-threat-or-advice-awesome.jpg)

**Comment by dibbhatt** [comment]
Thanks Frank.
I hope this will work for you. Do let me know if you find any issue.
Dib

**Comment by jedisct1** [comment]
Hi Dib,

I can get the Scala example (`examples/scala`) run any more:

```
INFO : org.apache.zookeeper.ZooKeeper - Initiating client connection, connectString=37.87.19.207:2181,37.87.19.208:2181,37.87.19.209:2181, sessionTimeout=120000 watcher=org.apache.curator.ConnectionState@c8bb86f
INFO : org.apache.zookeeper.ClientCnxn - Opening socket connection to server 37.87.19.207/37.87.19.207:2181. Will not attempt to authenticate using SASL (unknown error)
WARN : org.apache.zookeeper.ClientCnxn - Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.NoRouteToHostException: No route to host
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
```

But reverting to a version before today's changes, with exactly the same ZK quorum perfectly works.

Is there anything I can do in order to help you find what's wrong?

**Comment by dibbhatt** [comment]
I think the issue hapenning from ReceiverLauncher where I am trying to detect the number of Partition by connecting to ZK. Does your Driver machine from where you are launching the job have access to your ZK quorum ? I think no. Can you pls check that . ..

If not ; You can probabbly comment out the code in ReceiverLauncher where it get the number of partition and just hardcode the number and try ?

Dib


Sent from Samsung Mobile

Frank Denis <notifications@github.com> wrote:

Hi Dib,

I can get the Scala example (examples/scala) run any more:

INFO : org.apache.zookeeper.ZooKeeper - Initiating client connection, connectString=37.87.19.207:2181,37.87.19.208:2181,37.87.19.209:2181, sessionTimeout=120000 watcher=org.apache.curator.ConnectionState@c8bb86f
INFO : org.apache.zookeeper.ClientCnxn - Opening socket connection to server 37.87.19.207/37.87.19.207:2181. Will not attempt to authenticate using SASL (unknown error)
WARN : org.apache.zookeeper.ClientCnxn - Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.NoRouteToHostException: No route to host
    at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
    at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
    at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
    at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
But reverting to a version before today's changes, with exactly the same ZK quorum perfectly works.

Is there anything I can do in order to help you find what's wrong?
